In [1]:
%load_ext autoreload

In [2]:
%autoreload 1

In [3]:
import biom
import torch
import torch.nn as nn
%aimport mmvec.ALR

import numpy as np

torch.manual_seed(15)

In [4]:
microbes = biom.load_table("./soil_microbes.biom")
metabolites = biom.load_table("./soil_metabolites.biom")

model = mmvec.ALR.MMvecALR(microbes, metabolites, 15, sigma_u=1, sigma_v=1)

microbes = microbes.to_dataframe().T
metabolites = metabolites.to_dataframe().T
microbes = microbes.loc[metabolites.index]

microbe_idx = microbes.columns
metabolite_idx = metabolites.columns
microbes = torch.tensor(microbes.values, dtype=torch.int)
metabolites = torch.tensor(metabolites.values, dtype=torch.int64)

microbe_relative_frequency = (microbes.T/microbes.sum(1)).T

microbe_count = microbes.shape[1]
metabolite_count = metabolites.shape[1]

In [5]:
#model = mmvec.ALR.MMvecALR(microbe_count, metabolite_count, 15, sigma_u=1, sigma_v=1)
learning_rate = 1e-3
batch_size = 200
epochs = 100
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, maximize=True)

In [7]:
model.microbe_relative_freq

tensor([[0.2017, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0950, 0.1752, 0.0000,  ..., 0.0000, 0.0013, 0.0000],
        [0.1416, 0.0973, 0.0000,  ..., 0.0000, 0.0064, 0.0000],
        ...,
        [0.0507, 0.0000, 0.0090,  ..., 0.0058, 0.0000, 0.0051],
        [0.0382, 0.0076, 0.0025,  ..., 0.0000, 0.0009, 0.0100],
        [0.0027, 0.0135, 0.0000,  ..., 0.0000, 0.0008, 0.0036]])

In [6]:
maybe = mmvec.train.mmvec_training_loop(
                            model=model,
                            optimizer=optimizer,
                            batch_size=batch_size,
                            epochs=epochs)

torch.Size([200, 19])
tensor([[ 79, 139, 435,  ..., 189, 202, 335],
        [169, 433, 150,  ...,  68, 136, 224],
        [  9,   1, 224,  ..., 358, 224, 436],
        ...,
        [  0, 156,  71,  ..., 114, 402, 224],
        [143,   0,   0,  ...,   3, 189, 224],
        [ 39, 426,   4,  ...,  81, 280,  70]])
loss: -14241466368.0
Batch #: 0
torch.Size([200, 19])
tensor([[119, 424, 413,  ..., 103, 416, 335],
        [418, 126, 225,  ...,  26,   7, 129],
        [ 48,   1,   1,  ..., 224, 438, 224],
        ...,
        [224,   1, 324,  ..., 193,   0, 224],
        [418,   1, 224,  ..., 188,   0, 224],
        [ 21, 415,   0,  ..., 103, 224, 121]])
torch.Size([200, 19])
tensor([[284,   1, 191,  ...,  97, 137,  26],
        [  0, 174,  70,  ..., 440,  59, 335],
        [455, 158,  49,  ..., 451, 141, 147],
        ...,
        [455, 269,  70,  ..., 448, 335,   3],
        [158, 455, 335,  ..., 103,  59,  15],
        [431, 101, 191,  ...,   0, 125, 202]])
torch.Size([200, 19])
tensor([[4

torch.Size([200, 19])
tensor([[273,  12,   0,  ...,   0, 335, 437],
        [153, 464,   1,  ...,  97,  39,   1],
        [142, 433,  48,  ..., 103,  26, 181],
        ...,
        [428,   1, 271,  ..., 103, 413, 224],
        [  0,  31, 308,  ..., 448, 335, 422],
        [  3,   0, 435,  ..., 103, 264, 224]])
torch.Size([200, 19])
tensor([[452, 313,   1,  ..., 424, 302, 224],
        [ 34, 174, 335,  ...,  45, 336,  15],
        [ 72,  26, 295,  ...,  81, 252, 438],
        ...,
        [169,   0,  49,  ..., 147,  82, 112],
        [  0,  70, 170,  ..., 437, 147, 458],
        [  3,  87, 114,  ..., 103, 335,  37]])
torch.Size([200, 19])
tensor([[ 48, 198, 249,  ..., 103, 141, 336],
        [  0, 334, 180,  ..., 411, 419,  15],
        [439, 123,   0,  ..., 103,  80, 224],
        ...,
        [439, 412, 101,  ..., 430, 278,  15],
        [423,  84,   0,  ...,   0, 180, 436],
        [ 79,  34, 200,  ...,   0,  40, 440]])
torch.Size([200, 19])
tensor([[ 72, 114,   1,  ..., 147, 295, 44

torch.Size([200, 19])
tensor([[169, 158, 335,  ..., 115, 164, 335],
        [336,  31, 429,  ..., 136, 410, 422],
        [234, 358, 328,  ..., 451,  40, 224],
        ...,
        [  9, 234,  48,  ..., 402, 335, 461],
        [174, 455,   0,  ...,  97, 462,  15],
        [139, 156, 219,  ..., 424, 294,  15]])
torch.Size([200, 19])
tensor([[  0, 455, 324,  ..., 148, 354, 140],
        [ 92,  70, 258,  ..., 103, 279, 224],
        [439, 435,  48,  ...,  85, 215, 147],
        ...,
        [180,   1,   0,  ...,  32,  28, 224],
        [  0, 250,   0,  ..., 103, 441, 202],
        [  0,   1, 196,  ...,  97,  80, 336]])
torch.Size([200, 19])
tensor([[ 48,  70,   1,  ..., 314, 258, 440],
        [  0,   0,  48,  ..., 424, 105, 440],
        [  0,  35, 380,  ..., 437, 147, 434],
        ...,
        [228, 183,   4,  ..., 437, 224, 224],
        [206,  70, 224,  ..., 147, 335, 224],
        [460, 269,  48,  ..., 424, 431,  18]])
torch.Size([200, 19])
tensor([[439,   1,  12,  ..., 314, 231, 11

torch.Size([200, 19])
tensor([[ 48,   1,  26,  ..., 424, 356, 235],
        [  0,   0,  20,  ..., 114, 423, 437],
        [191,   1, 299,  ..., 103, 425, 440],
        ...,
        [100,  67,   1,  ..., 437,  37,  94],
        [  0,  70, 118,  ..., 103, 332, 422],
        [ 73, 455,   0,  ..., 455, 441, 224]])
torch.Size([200, 19])
tensor([[439,   1,  93,  ...,  64,  40, 224],
        [ 67,   3, 294,  ...,  64, 224, 440],
        [169, 337,   1,  ..., 147, 146,   1],
        ...,
        [444, 423,  48,  ...,  81, 335,  38],
        [439,   1,  48,  ..., 103,   0, 420],
        [  0,   0,  48,  ..., 426, 221, 224]])
torch.Size([200, 19])
tensor([[ 59,   1,   0,  ..., 317, 105, 335],
        [439,   1, 224,  ..., 414,  37, 440],
        [ 70,   1,   0,  ...,   3, 295, 436],
        ...,
        [415,   1,   0,  ..., 136, 224, 335],
        [213,   0,   1,  ..., 103, 411, 436],
        [  0,   0,   0,  ..., 358, 414,   1]])


In [11]:
model.ranks()

In [12]:
# h = model.ranks_df - model.ranks_df.mean(axis=0)
h = model.ranks_matrix

k = model.latent_dim

In [ ]:
h.mean(dim=0).shape

In [ ]:
from torch.linalg import svd


In [ ]:
u, s, v = svd(h, full_matrices=False)

In [ ]:
u.shape, s.shape, v.shape

In [ ]:
s

In [13]:
model.ranks_df

(2,3-dihydroxy-3-methylbutanoate)  \
rplo 1 (Cyanobacteria)                             1.175766   
rplo 2 (Firmicutes)                                0.258168   
rplo 60 (Firmicutes)                               0.958025   
rplo 7 (Actinobacteria)                            0.919803   
rplo 10 (Firmicutes)                               1.143667   
...                                                     ...   
rplo 95 (Proteobacteria)                          -0.897942   
rplo 96 (unknown)                                  0.871905   
rplo 97 (Firmicutes)                               0.064521   
rplo 98 (Actinobacteria)                           0.400170   
rplo 99 (Cyanobacteria)                            1.129443   

                          (2,5-diaminohexanoate)  (3-hydroxypyridine)  \
rplo 1 (Cyanobacteria)                  0.067746            -0.552615   
rplo 2 (Firmicutes)                    -0.744190             0.057575   
rplo 60 (Firmicutes)                   -0.507875            -0.893401   
rplo 7 (Actinobacteria)                 0.355543            -0.450468   
rplo 10 (Firmicutes)                   -0.617700            -0.693222   
...                                          ...                  ...   
rplo 95 (Proteobacteria)                0.236029            -0.405040   
rplo 96 (unknown)                       0.071470            -0.382577   
rplo 97 (Firmicutes)                    0.104134            -0.882605   
rplo 98 (Actinobacteria)                0.120926            -0.454491   
rplo 99 (Cyanobacteria)                -0.654812            -0.016671   

                          (3-methyladenine)  (4-oxoproline)  \
rplo 1 (Cyanobacteria)            -0.175478        0.625556   
rplo 2 (Firmicutes)               -0.139843        0.546534   
rplo 60 (Firmicutes)               0.241754       -0.286902   
rplo 7 (Actinobacteria)           -0.376922        0.442490   
rplo 10 (Firmicutes)               0.199539        0.394505   
...                                     ...             ...   
rplo 95 (Proteobacteria)          -0.371427        0.381187   
rplo 96 (unknown)                 -0.089850        0.099791   
rplo 97 (Firmicutes)              -0.478958       -0.463571   
rplo 98 (Actinobacteria)          -0.027568        0.462932   
rplo 99 (Cyanobacteria)            0.042046        0.232794   

                          (5,6-dihydrothymine)  (alanyl-leucine)  \
rplo 1 (Cyanobacteria)                0.071818          0.807590   
rplo 2 (Firmicutes)                  -0.165667          0.343791   
rplo 60 (Firmicutes)                 -0.043752          0.272253   
rplo 7 (Actinobacteria)               0.049498          0.419829   
rplo 10 (Firmicutes)                 -0.239950         -0.174597   
...                                        ...               ...   
rplo 95 (Proteobacteria)             -0.011043          0.139877   
rplo 96 (unknown)                     0.226773         -0.217144   
rplo 97 (Firmicutes)                 -0.645346          0.043512   
rplo 98 (Actinobacteria)             -0.809299          0.197001   
rplo 99 (Cyanobacteria)               0.002960          0.087835   

                          (dehydroalanine)  (glycero-3-phosphoethanolamine)  \
rplo 1 (Cyanobacteria)           -0.603510                        -0.627171   
rplo 2 (Firmicutes)              -0.439517                        -0.666039   
rplo 60 (Firmicutes)              0.417226                        -0.292448   
rplo 7 (Actinobacteria)           0.183686                         0.026987   
rplo 10 (Firmicutes)              0.046950                         0.183876   
...                                    ...                              ...   
rplo 95 (Proteobacteria)          0.228063                         0.103917   
rplo 96 (unknown)                 0.769984                         0.784919   
rplo 97 (Firmicutes)              0.436498                         0.919183   
rplo 98 (Actinobacteria)    

In [48]:
model.get_ordination()

torch.Size([466, 85])
torch.Size([85])
torch.Size([85, 85])
torch.Size([466])
tensor([ -1.1445,  -6.3680,  -4.3185,   4.9945,  -1.4082,  -8.2258,   1.8486,
         -4.3756,   4.7173,  -6.9559,   3.2740,   0.4376,  -5.9801,   6.3349,
          1.0003,  -8.6350,   2.8014,   0.6915,   1.2820,  -4.5347,   4.0379,
         -5.6501,   1.9838,   0.2808,  -0.2633,  -3.2443,  -4.1948,   1.5267,
         -1.1784,  -2.8921,   2.6564,   1.6168,  -0.1698,  -0.9756,  -4.8180,
         -4.7775,   1.7069,  -1.3242,  -4.7067,   0.6504,  -5.5535,   4.1691,
         -2.5773,   4.0220,  -2.2959,  -6.7313,  -6.9085,   1.4211,   3.6404,
          1.5132,   2.4939,   0.5881,   1.9394,   7.5292,  -8.3888,  -0.6539,
         10.1397,  -2.4303,  -3.2335,   1.4971,  -1.7446,   2.4674,   3.4813,
          0.0457,   0.8573,   3.2580,  -3.3791,   3.7058,   4.9621,  -1.6585,
          0.2361,   0.1459,   4.4815,  -4.4632,   7.9341,  -3.4729,   6.7684,
         -3.3562,   2.3691,   6.9417,   5.4023,  -0.2494,   6.69

In [ ]:
ranks = pd.DataFrame(model.ranks(),
                     index=microbe_idx,
                     columns=metabolite_idx)

In [ ]:
ranks

In [ ]:
for param in model.parameters():
    print(param.shape)

print(model.parameters)

In [115]:
a = torch.randint(10, (9, 3), dtype=torch.float)
b = torch.randint(10, (3,))
a, a - a.mean(dim=0), a.mean(dim=0)

(tensor([[9., 6., 7.],
         [3., 8., 2.],
         [6., 5., 3.],
         [4., 6., 4.],
         [7., 5., 0.],
         [6., 0., 3.],
         [2., 4., 3.],
         [5., 4., 9.],
         [7., 3., 1.]]),
 tensor([[ 3.5556,  1.4444,  3.4444],
         [-2.4444,  3.4444, -1.5556],
         [ 0.5556,  0.4444, -0.5556],
         [-1.4444,  1.4444,  0.4444],
         [ 1.5556,  0.4444, -3.5556],
         [ 0.5556, -4.5556, -0.5556],
         [-3.4444, -0.5556, -0.5556],
         [-0.4444, -0.5556,  5.4444],
         [ 1.5556, -1.5556, -2.5556]]),
 tensor([5.4444, 4.5556, 3.5556]))

In [91]:
bp = model.get_ordination()

torch.Size([466, 85])
torch.Size([85])
torch.Size([85, 85])
compare unmodified:
tensor([3.9370e+01, 3.0685e+01, 2.7607e+01, 2.6057e+01, 2.4771e+01, 2.4166e+01,
        2.3556e+01, 2.1152e+01, 2.0435e+01, 1.9499e+01, 1.8038e+01, 1.7893e+01,
        1.6577e+01, 1.5838e+01, 1.4549e+01, 8.0469e+00, 1.3352e-05, 7.6159e-06,
        6.4840e-06, 5.7771e-06, 5.1234e-06, 4.8650e-06, 4.7076e-06, 4.3261e-06,
        3.7033e-06, 3.3649e-06, 3.2426e-06, 3.1312e-06, 2.9980e-06, 2.9524e-06,
        2.7562e-06, 2.7255e-06, 2.5842e-06, 2.5818e-06, 2.5675e-06, 2.5544e-06,
        2.5496e-06, 2.5244e-06, 2.5015e-06, 2.4779e-06, 2.4762e-06, 2.4727e-06,
        2.4645e-06, 2.4528e-06, 2.4424e-06, 2.4378e-06, 2.4306e-06, 2.4263e-06,
        2.4155e-06, 2.3750e-06, 2.2824e-06, 2.2305e-06, 2.2250e-06, 2.2146e-06,
        2.2125e-06, 2.1982e-06, 2.1954e-06, 2.1732e-06, 2.1682e-06, 2.1579e-06,
        2.1559e-06, 2.1535e-06, 2.1495e-06, 2.1278e-06, 2.0853e-06, 2.0755e-06,
        2.0694e-06, 2.0658e-06, 2.0506e-

In [116]:
import os.path

In [117]:
bp_path = os.path.join("/Users/keeganevans/Desktop/", "biplot")

In [118]:
bp.write(bp_path)

'/Users/keeganevans/Desktop/biplot'